apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forecasting-prod
resources:
  - ../base
  - namespace.yaml
  - service-account.yaml
  - configmap-env.yaml
  - secret-provider-class.yaml
patches:
  - path: deployment-patch.yaml
