apiVersion: v1
kind: ServiceAccount
metadata:
  name: forecasting-prod-ksa
  namespace: forecasting-prod
  annotations:
    iam.gke.io/gcp-service-account: forecasting-prod-sa@ethans-services.iam.gserviceaccount.com
