apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: forecasting-staging-secrets
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/ethans-services/secrets/forecasting_staging_database_url/versions/latest"
        path: "DATABASE_URL"
      - resourceName: "projects/ethans-services/secrets/forecasting_staging_jwt_secret/versions/latest"
        path: "JWT_SECRET"
      - resourceName: "projects/ethans-services/secrets/forecasting_staging_argon2_salt/versions/latest"
        path: "ARGON2_SALT"
      - resourceName: "projects/ethans-services/secrets/forecasting_staging_idp_client_id/versions/latest"
        path: "IDP_CLIENT_ID"
      - resourceName: "projects/ethans-services/secrets/forecasting_staging_idp_client_secret/versions/latest"
        path: "IDP_CLIENT_SECRET"
  secretObjects:
    - secretName: forecasting-staging-secrets
      type: Opaque
      data:
        - objectName: "DATABASE_URL"
          key: DATABASE_URL
        - objectName: "JWT_SECRET"
          key: JWT_SECRET
        - objectName: "ARGON2_SALT"
          key: ARGON2_SALT
        - objectName: "IDP_CLIENT_ID"
          key: IDP_CLIENT_ID
        - objectName: "IDP_CLIENT_SECRET"
          key: IDP_CLIENT_SECRET
