apiVersion: v1
kind: ServiceAccount
metadata:
  name: forecasting-staging-ksa
  namespace: forecasting-staging
  annotations:
    iam.gke.io/gcp-service-account: forecasting-staging-sa@ethans-services.iam.gserviceaccount.com
