apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forecasting-staging-ts
spec:
  defaultBackend:
    service:
      name: forecasting
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - forecasting-staging
